### ISSUE TITLE
cannot import TabularExplainer from interpret.ext.blackbox

### ISSUE THREAD

**Issue by arbitor1999** [interpretml/interpret-community#298]
**Describe the bug**
Help! Just cannot import TabularExplainer from interpret.ext.blackbox. My interpret version is 0.2.1 and python version is 3.7. Not know if that is the reason?
![89726026-8dd0e700-da48-11ea-921f-f0b1dac47544](https://user-images.githubusercontent.com/59723783/89726421-f02be680-da4c-11ea-801f-aace0528629c.png)

I copy the code from a Microsoft tutorial...
![89726051-cec8fb80-da48-11ea-8d4e-e7c0a401cf2b](https://user-images.githubusercontent.com/59723783/89726392-b4911c80-da4c-11ea-8f2c-8e34fddc2152.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by imatiach-msft** [comment]
@arbitor1999 I think the issue may be due to the dependency on interpret-core being newer than supported, I created a PR here:
https://github.com/interpretml/interpret-community/pull/299
Usually this issue is caused by conflicting dependencies, which breaks the extension system.
There should be some warning message coming from interpret when installing interpret-community:
https://github.com/interpretml/interpret/blob/master/python/interpret-core/interpret/ext/extension_utils.py#L66

**Comment by imatiach-msft** [comment]
@arbitor1999 a new version of interpret-community has been released, 0.14.2, which depends on the newer version of interpret -- did that fix the issue for you?

**Comment by arbitor1999** [comment]
Actually not... My interpret version is 0.2.1 and interpret-community version is 0.14.2. Here is the error I got.
![报错](https://user-images.githubusercontent.com/59723783/90158660-da5a5080-ddc1-11ea-9f97-f7edcb527462.png)
![报错2](https://user-images.githubusercontent.com/59723783/90158666-db8b7d80-ddc1-11ea-80ba-86839c16fdb3.png)
Thank you for helping me with the error! I guess there is still some conflicting dependencies...

**Comment by arbitor1999** [comment]
@imatiach-msft

**Comment by imatiach-msft** [comment]
@arbitor1999 oh no you are right, it looks like there was a breaking change in latest interpret 0.2.1, and apparently when I updated the setup.py I didn't update our tests in https://github.com/interpretml/interpret-community/blob/master/requirements.txt, effectively not testing on the latest version.  I've sent a PR to fix it:
https://github.com/interpretml/interpret-community/pull/304
will do a new pypi release right after I've confirmed all tests are successful.

**Comment by imatiach-msft** [comment]
@arbitor1999  I just released 0.14.3 recently with the hotfix, the issue should be fixed now

**Comment by imatiach-msft** [comment]
@arbitor1999 are you still running into this issue with the latest package?

**Comment by arbitor1999** [comment]
No. The problem is solved. Thank you.

**Comment by arbitor1999** [comment]
@imatiach-msft

**Comment by imatiach-msft** [comment]
thanks for confirming, closing the issue

**Comment by anindya5** [comment]
@imatiach-msft  I am starting today, and getting this error

**Comment by frvigano** [comment]
I am experiencing the same issue. I tried to install version 0.14.3 but still not able to solve the issue

**Comment by stephlocke** [comment]
+1
